# Site settings
title: Hathaway Digital
email: mike@mikehathaway.com
description: > # this means to ignore newlines until "baseurl:"
Hathaway Digital proven consulting for your digital life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hathawaydigital.com" # the base hostname & protocol for your site

# User setting
owner: Mike Hathaway
email: mike@mikehathaway.com
facebook_username: miehathaway
twitter_username: mikehathaway
github_username: mjh2901
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:  
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
